-- FlyMasar — Full Effective Database Schema (authoritative)
-- Generated by applying all migrations 001–078 in order, then dumping the result.
-- 65 tables. This is the source of truth for exact columns, types, keys, and FKs.

CREATE TABLE `admin_activity_log` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `admin_id` int(10) unsigned NOT NULL,
  `action` varchar(100) NOT NULL,
  `module` varchar(50) NOT NULL,
  `entity_type` varchar(50) DEFAULT NULL,
  `entity_id` int(10) unsigned DEFAULT NULL,
  `description` text DEFAULT NULL,
  `ip_address` varchar(45) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `idx_admin` (`admin_id`),
  KEY `idx_module` (`module`,`created_at`),
  CONSTRAINT `admin_activity_log_ibfk_1` FOREIGN KEY (`admin_id`) REFERENCES `users` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci
;

CREATE TABLE `admin_sessions` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `user_id` int(10) unsigned NOT NULL,
  `token` varchar(64) NOT NULL,
  `ip_address` varchar(45) DEFAULT NULL,
  `user_agent` text DEFAULT NULL,
  `last_active_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `expires_at` datetime NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_token` (`token`),
  KEY `idx_user_id` (`user_id`),
  CONSTRAINT `admin_sessions_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci
;

CREATE TABLE `airlines` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `iata_code` char(2) NOT NULL,
  `icao_code` char(3) DEFAULT NULL,
  `name_en` varchar(150) NOT NULL,
  `name_ar` varchar(150) DEFAULT NULL,
  `country_id` smallint(5) unsigned DEFAULT NULL,
  `logo_url` varchar(300) DEFAULT NULL,
  `is_active` tinyint(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_iata` (`iata_code`),
  KEY `idx_country` (`country_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci
;

CREATE TABLE `airports` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `iata_code` char(3) NOT NULL,
  `icao_code` char(4) DEFAULT NULL,
  `name_en` varchar(200) NOT NULL,
  `name_ar` varchar(200) DEFAULT NULL,
  `city_id` int(10) unsigned NOT NULL,
  `country_id` smallint(5) unsigned NOT NULL,
  `latitude` decimal(9,6) DEFAULT NULL,
  `longitude` decimal(9,6) DEFAULT NULL,
  `timezone` varchar(50) DEFAULT NULL,
  `is_active` tinyint(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_iata` (`iata_code`),
  KEY `idx_city` (`city_id`),
  KEY `country_id` (`country_id`),
  CONSTRAINT `airports_ibfk_1` FOREIGN KEY (`city_id`) REFERENCES `cities` (`id`),
  CONSTRAINT `airports_ibfk_2` FOREIGN KEY (`country_id`) REFERENCES `countries` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci
;

CREATE TABLE `api_settings` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `provider` varchar(50) NOT NULL,
  `setting_key` varchar(100) NOT NULL,
  `setting_value` text DEFAULT NULL,
  `is_secret` tinyint(1) NOT NULL DEFAULT 0,
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_provider_key` (`provider`,`setting_key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci
;

CREATE TABLE `attachments` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `entity_type` varchar(50) NOT NULL,
  `entity_id` int(10) unsigned NOT NULL,
  `file_name` varchar(255) NOT NULL,
  `file_path` varchar(400) NOT NULL,
  `file_size` int(11) DEFAULT NULL,
  `mime_type` varchar(100) DEFAULT NULL,
  `uploaded_by` int(10) unsigned DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `idx_entity` (`entity_type`,`entity_id`),
  KEY `uploaded_by` (`uploaded_by`),
  CONSTRAINT `attachments_ibfk_1` FOREIGN KEY (`uploaded_by`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci
;

CREATE TABLE `booking_audit_log` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `booking_type` enum('flight','hotel') NOT NULL,
  `booking_id` int(10) unsigned NOT NULL,
  `action` varchar(50) NOT NULL,
  `changed_by` int(10) unsigned DEFAULT NULL,
  `changed_by_type` enum('user','admin','system','webhook') NOT NULL DEFAULT 'system',
  `before_data` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`before_data`)),
  `after_data` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`after_data`)),
  `notes` text DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `idx_booking` (`booking_type`,`booking_id`),
  KEY `idx_changed_by` (`changed_by`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci
;

CREATE TABLE `booking_pricing_breakdown` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `booking_type` enum('flight','hotel') NOT NULL,
  `booking_id` int(10) unsigned NOT NULL,
  `item_type` varchar(50) NOT NULL,
  `description_en` varchar(200) DEFAULT NULL,
  `description_ar` varchar(200) DEFAULT NULL,
  `quantity` tinyint(4) NOT NULL DEFAULT 1,
  `unit_price` decimal(10,2) NOT NULL,
  `total_price` decimal(10,2) NOT NULL,
  `currency` char(3) NOT NULL DEFAULT 'GBP',
  PRIMARY KEY (`id`),
  KEY `idx_booking` (`booking_type`,`booking_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci
;

CREATE TABLE `booking_sessions` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `session_key` varchar(64) NOT NULL,
  `user_id` int(10) unsigned NOT NULL,
  `booking_type` enum('flight','hotel') NOT NULL DEFAULT 'flight',
  `current_step` varchar(30) NOT NULL DEFAULT 'search',
  `provider_offer_id` varchar(100) DEFAULT NULL,
  `offer_expires_at` datetime DEFAULT NULL,
  `prebook_session_id` varchar(200) DEFAULT NULL,
  `passengers_data` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`passengers_data`)),
  `services_data` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`services_data`)),
  `guests_data` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`guests_data`)),
  `pricing_snapshot` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`pricing_snapshot`)),
  `coupon_code` varchar(30) DEFAULT NULL,
  `payment_intent_id` varchar(100) DEFAULT NULL,
  `idempotency_key` varchar(64) DEFAULT NULL,
  `expires_at` datetime NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `device_ip` varchar(45) DEFAULT NULL COMMENT 'Client IP forwarded to Duffel for fraud detection',
  `device_user_agent` varchar(500) DEFAULT NULL COMMENT 'Client User-Agent forwarded to Duffel for fraud detection',
  `total_amount` decimal(10,2) DEFAULT NULL COMMENT 'Cached total including services, used for services cost display',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_session_key` (`session_key`),
  KEY `idx_user_type` (`user_id`,`booking_type`),
  KEY `idx_expires` (`expires_at`),
  KEY `idx_payment_intent` (`payment_intent_id`),
  CONSTRAINT `booking_sessions_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci
;

CREATE TABLE `cities` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `country_id` smallint(5) unsigned NOT NULL,
  `name_en` varchar(150) NOT NULL,
  `name_ar` varchar(150) DEFAULT NULL,
  `iata_city_code` char(3) DEFAULT NULL,
  `latitude` decimal(9,6) DEFAULT NULL,
  `longitude` decimal(9,6) DEFAULT NULL,
  `is_active` tinyint(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  KEY `idx_country` (`country_id`),
  CONSTRAINT `cities_ibfk_1` FOREIGN KEY (`country_id`) REFERENCES `countries` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci
;

CREATE TABLE `cms_pages` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `slug` varchar(100) NOT NULL,
  `title_en` varchar(200) NOT NULL,
  `title_ar` varchar(200) NOT NULL,
  `content_en` longtext DEFAULT NULL,
  `content_ar` longtext DEFAULT NULL,
  `meta_title_en` varchar(200) DEFAULT NULL,
  `meta_desc_en` varchar(300) DEFAULT NULL,
  `meta_title_ar` varchar(200) DEFAULT NULL,
  `meta_desc_ar` varchar(300) DEFAULT NULL,
  `is_published` tinyint(1) NOT NULL DEFAULT 0,
  `published_at` timestamp NULL DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_slug` (`slug`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci
;

CREATE TABLE `commissions` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `type` enum('flight','hotel','all') NOT NULL DEFAULT 'flight',
  `name` varchar(200) NOT NULL,
  `commission_type` enum('percentage','fixed') NOT NULL DEFAULT 'percentage',
  `commission_value` decimal(10,4) NOT NULL DEFAULT 0.0000,
  `applies_to` varchar(50) NOT NULL DEFAULT 'all',
  `condition_value` varchar(200) DEFAULT NULL,
  `is_active` tinyint(1) NOT NULL DEFAULT 1,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci
;

CREATE TABLE `countries` (
  `id` smallint(5) unsigned NOT NULL AUTO_INCREMENT,
  `iso2` char(2) NOT NULL,
  `iso3` char(3) NOT NULL,
  `name_en` varchar(100) NOT NULL,
  `name_ar` varchar(100) DEFAULT NULL,
  `phone_code` varchar(6) DEFAULT NULL,
  `currency_code` char(3) DEFAULT NULL,
  `is_active` tinyint(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_iso2` (`iso2`),
  UNIQUE KEY `uq_iso3` (`iso3`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci
;

CREATE TABLE `coupons` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `code` varchar(30) NOT NULL,
  `discount_type` enum('fixed','percentage') NOT NULL,
  `discount_value` decimal(10,2) NOT NULL,
  `currency` char(3) DEFAULT NULL,
  `max_discount_amount` decimal(10,2) DEFAULT NULL,
  `applies_to` enum('flight','hotel','both') NOT NULL DEFAULT 'both',
  `min_booking_amount` decimal(10,2) DEFAULT NULL,
  `usage_limit` int(11) DEFAULT NULL,
  `usage_count` int(11) NOT NULL DEFAULT 0,
  `user_id` int(10) unsigned DEFAULT NULL,
  `valid_from` datetime NOT NULL,
  `valid_until` datetime NOT NULL,
  `is_active` tinyint(1) NOT NULL DEFAULT 1,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_code` (`code`),
  KEY `idx_active` (`is_active`,`valid_from`,`valid_until`),
  KEY `user_id` (`user_id`),
  CONSTRAINT `coupons_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci
;

CREATE TABLE `coupon_usages` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `coupon_id` int(10) unsigned NOT NULL,
  `user_id` int(10) unsigned NOT NULL,
  `booking_type` enum('flight','hotel') NOT NULL,
  `booking_id` int(10) unsigned NOT NULL,
  `discount_applied` decimal(10,2) NOT NULL,
  `used_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `idx_coupon` (`coupon_id`),
  KEY `idx_user` (`user_id`),
  CONSTRAINT `coupon_usages_ibfk_1` FOREIGN KEY (`coupon_id`) REFERENCES `coupons` (`id`),
  CONSTRAINT `coupon_usages_ibfk_2` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci
;

CREATE TABLE `currencies` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `code` char(3) NOT NULL,
  `name` varchar(100) NOT NULL,
  `symbol` varchar(10) DEFAULT NULL,
  `rate_to_gbp` decimal(18,6) NOT NULL DEFAULT 1.000000,
  `is_active` tinyint(1) NOT NULL DEFAULT 1,
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_code` (`code`)
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci
;

CREATE TABLE `error_logs` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `level` enum('debug','info','warning','error','critical') NOT NULL DEFAULT 'error',
  `message` text NOT NULL,
  `context` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`context`)),
  `file` varchar(300) DEFAULT NULL,
  `line` int(11) DEFAULT NULL,
  `user_id` int(10) unsigned DEFAULT NULL,
  `ip_address` varchar(45) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `idx_level_date` (`level`,`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci
;

CREATE TABLE `exchange_rates` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `from_currency` char(3) NOT NULL,
  `to_currency` char(3) NOT NULL,
  `rate` decimal(15,6) NOT NULL,
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_pair` (`from_currency`,`to_currency`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci
;

CREATE TABLE `flight_bookings` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `user_id` int(10) unsigned NOT NULL,
  `provider_id` tinyint(3) unsigned NOT NULL,
  `booking_reference` varchar(30) NOT NULL,
  `provider_order_id` varchar(100) DEFAULT NULL,
  `provider_offer_id` varchar(100) DEFAULT NULL COMMENT 'Duffel offer_id used to create this order',
  `duffel_booking_reference` varchar(30) DEFAULT NULL COMMENT 'Airline PNR from Duffel order.booking_reference',
  `pending_cancellation_id` varchar(100) DEFAULT NULL,
  `trip_type` enum('one_way','round_trip','multi_city') NOT NULL,
  `cabin_class` enum('economy','premium_economy','business','first') NOT NULL DEFAULT 'economy',
  `adults_count` tinyint(4) NOT NULL DEFAULT 1,
  `children_count` tinyint(4) NOT NULL DEFAULT 0,
  `infants_count` tinyint(4) NOT NULL DEFAULT 0,
  `origin_airport` char(3) NOT NULL,
  `destination_airport` char(3) NOT NULL,
  `departure_at` datetime NOT NULL,
  `return_at` datetime DEFAULT NULL,
  `total_amount` decimal(10,2) NOT NULL,
  `currency` char(3) NOT NULL DEFAULT 'GBP',
  `status` enum('pending','confirmed','cancelled','changed','awaiting_payment','failed') NOT NULL DEFAULT 'pending' COMMENT 'Booking lifecycle status',
  `cancellation_reason` text DEFAULT NULL,
  `cancelled_at` timestamp NULL DEFAULT NULL,
  `cancellation_refund_amount` decimal(12,2) DEFAULT NULL,
  `paid_at` datetime DEFAULT NULL COMMENT 'payment_status.paid_at from Duffel',
  `payment_required_by` datetime DEFAULT NULL COMMENT 'payment_status.payment_required_by — booking expires',
  `price_guarantee_expires_at` datetime DEFAULT NULL COMMENT 'payment_status.price_guarantee_expires_at',
  `void_window_ends_at` datetime DEFAULT NULL COMMENT 'order.void_window_ends_at — free-cancel deadline',
  `available_actions` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'order.available_actions array' CHECK (json_valid(`available_actions`)),
  `synced_at` datetime DEFAULT NULL COMMENT 'Last Duffel getOrder() refresh timestamp',
  `live_mode` tinyint(1) NOT NULL DEFAULT 1 COMMENT 'order.live_mode (0=test, 1=live)',
  `cancellation_refund_to` varchar(60) DEFAULT NULL COMMENT 'cancellation.refund_to field from Duffel',
  `cancellation_expires_at` datetime DEFAULT NULL COMMENT 'cancellation.expires_at — quote validity deadline',
  `refund_conditions` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'conditions.refund_before_departure from order/offer' CHECK (json_valid(`refund_conditions`)),
  `change_conditions` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'conditions.change_before_departure from order/offer' CHECK (json_valid(`change_conditions`)),
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `awaiting_payment` tinyint(1) NOT NULL DEFAULT 0 COMMENT 'Set when Duffel flags order.payment_status.awaiting_payment',
  `duffel_payment_failure` varchar(500) DEFAULT NULL COMMENT 'Duffel failure_reason or order creation error',
  `cancellation_refund_currency` char(3) DEFAULT NULL COMMENT 'Currency of Duffel refund_amount (may differ from charge currency)',
  `auto_refunded_at` datetime DEFAULT NULL COMMENT 'Timestamp of automatic Stripe refund on Duffel order failure',
  `booking_references` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'order.booking_references[] from Duffel — per-airline PNR array' CHECK (json_valid(`booking_references`)),
  `cancellation_confirmed_at` datetime DEFAULT NULL COMMENT 'Duffel order_cancellation.confirmed_at — when the cancellation was confirmed by airline',
  `change_fee_paid` decimal(10,2) DEFAULT NULL COMMENT 'Total change fees paid by customer (cumulative)',
  `refund_preference` enum('wallet','original_payment') DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_booking_ref` (`booking_reference`),
  KEY `idx_user_status` (`user_id`,`status`),
  KEY `idx_provider` (`provider_id`),
  KEY `idx_payment_deadline` (`payment_required_by`),
  KEY `idx_duffel_booking_ref` (`duffel_booking_reference`),
  KEY `idx_provider_offer` (`provider_offer_id`),
  CONSTRAINT `flight_bookings_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`),
  CONSTRAINT `flight_bookings_ibfk_2` FOREIGN KEY (`provider_id`) REFERENCES `providers` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci
;

CREATE TABLE `flight_booking_documents` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `booking_id` int(10) unsigned NOT NULL,
  `document_type` varchar(50) NOT NULL COMMENT 'electronic_ticket | boarding_pass | itinerary',
  `unique_identifier` varchar(50) NOT NULL COMMENT 'Ticket number / document unique ID from Duffel',
  `passenger_ids` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'Array of Duffel passenger IDs this document covers' CHECK (json_valid(`passenger_ids`)),
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_booking_doc` (`booking_id`,`unique_identifier`),
  KEY `idx_booking` (`booking_id`),
  CONSTRAINT `flight_booking_documents_ibfk_1` FOREIGN KEY (`booking_id`) REFERENCES `flight_bookings` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci
;

CREATE TABLE `flight_booking_passengers` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `booking_id` int(10) unsigned NOT NULL,
  `traveler_id` int(10) unsigned DEFAULT NULL,
  `passenger_type` enum('adult','child','infant') NOT NULL,
  `first_name` varchar(80) NOT NULL,
  `last_name` varchar(80) NOT NULL,
  `gender` enum('male','female') NOT NULL,
  `date_of_birth` date NOT NULL,
  `nationality` char(2) NOT NULL,
  `passport_number` varchar(30) DEFAULT NULL,
  `passport_expiry` date DEFAULT NULL,
  `ticket_number` varchar(20) DEFAULT NULL,
  `provider_passenger_id` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_booking` (`booking_id`),
  KEY `traveler_id` (`traveler_id`),
  CONSTRAINT `flight_booking_passengers_ibfk_1` FOREIGN KEY (`booking_id`) REFERENCES `flight_bookings` (`id`) ON DELETE CASCADE,
  CONSTRAINT `flight_booking_passengers_ibfk_2` FOREIGN KEY (`traveler_id`) REFERENCES `travelers` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci
;

CREATE TABLE `flight_booking_segments` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `booking_id` int(10) unsigned NOT NULL,
  `slice_index` tinyint(4) NOT NULL DEFAULT 0,
  `segment_order` tinyint(4) NOT NULL DEFAULT 1,
  `flight_number` varchar(10) NOT NULL,
  `airline_code` char(2) NOT NULL,
  `aircraft_type` varchar(50) DEFAULT NULL,
  `origin_airport` char(3) NOT NULL,
  `destination_airport` char(3) NOT NULL,
  `departure_at` datetime NOT NULL,
  `arrival_at` datetime NOT NULL,
  `duration_minutes` smallint(6) DEFAULT NULL,
  `cabin_class` enum('economy','premium_economy','business','first') NOT NULL DEFAULT 'economy',
  `is_overnight` tinyint(1) NOT NULL DEFAULT 0,
  `baggage_info` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`baggage_info`)),
  PRIMARY KEY (`id`),
  KEY `idx_booking` (`booking_id`),
  KEY `idx_booking_slice` (`booking_id`,`slice_index`),
  KEY `idx_airline` (`airline_code`),
  CONSTRAINT `flight_booking_segments_ibfk_1` FOREIGN KEY (`booking_id`) REFERENCES `flight_bookings` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci
;

CREATE TABLE `flight_booking_services` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `booking_id` int(10) unsigned NOT NULL,
  `passenger_id` int(10) unsigned NOT NULL,
  `service_type` enum('bag','seat','meal','other') NOT NULL,
  `service_detail` varchar(200) DEFAULT NULL,
  `provider_service_id` varchar(100) DEFAULT NULL,
  `amount` decimal(8,2) NOT NULL DEFAULT 0.00,
  `currency` char(3) NOT NULL DEFAULT 'GBP',
  PRIMARY KEY (`id`),
  KEY `idx_booking` (`booking_id`),
  KEY `passenger_id` (`passenger_id`),
  CONSTRAINT `flight_booking_services_ibfk_1` FOREIGN KEY (`booking_id`) REFERENCES `flight_bookings` (`id`) ON DELETE CASCADE,
  CONSTRAINT `flight_booking_services_ibfk_2` FOREIGN KEY (`passenger_id`) REFERENCES `flight_booking_passengers` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci
;

CREATE TABLE `hotels_content` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `provider_id` tinyint(3) unsigned NOT NULL,
  `provider_hotel_id` varchar(100) NOT NULL,
  `name_en` varchar(300) NOT NULL,
  `name_ar` varchar(300) DEFAULT NULL,
  `star_rating` tinyint(4) DEFAULT NULL,
  `guest_rating` decimal(3,1) DEFAULT NULL,
  `reviews_count` int(11) DEFAULT NULL,
  `address_en` text DEFAULT NULL,
  `address_ar` text DEFAULT NULL,
  `city_id` int(10) unsigned DEFAULT NULL,
  `country_id` smallint(5) unsigned DEFAULT NULL,
  `latitude` decimal(9,6) DEFAULT NULL,
  `longitude` decimal(9,6) DEFAULT NULL,
  `distance_to_center_km` decimal(5,2) DEFAULT NULL,
  `images_count` tinyint(4) NOT NULL DEFAULT 0,
  `main_image_url` varchar(500) DEFAULT NULL,
  `amenities` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`amenities`)),
  `description_en` text DEFAULT NULL,
  `description_ar` text DEFAULT NULL,
  `policies` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`policies`)),
  `children_policy` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`children_policy`)),
  `is_active` tinyint(1) NOT NULL DEFAULT 1,
  `content_updated_at` timestamp NULL DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_provider_hotel` (`provider_id`,`provider_hotel_id`),
  KEY `idx_city` (`city_id`),
  KEY `idx_country` (`country_id`),
  KEY `idx_star_active` (`star_rating`,`is_active`),
  KEY `idx_guest_rating` (`guest_rating`),
  CONSTRAINT `hotels_content_ibfk_1` FOREIGN KEY (`provider_id`) REFERENCES `providers` (`id`),
  CONSTRAINT `hotels_content_ibfk_2` FOREIGN KEY (`city_id`) REFERENCES `cities` (`id`) ON DELETE SET NULL,
  CONSTRAINT `hotels_content_ibfk_3` FOREIGN KEY (`country_id`) REFERENCES `countries` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci
;

CREATE TABLE `hotel_bookings` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `user_id` int(10) unsigned NOT NULL,
  `provider_id` tinyint(3) unsigned NOT NULL,
  `booking_reference` varchar(30) NOT NULL,
  `provider_booking_id` varchar(100) DEFAULT NULL,
  `hotel_id` int(10) unsigned NOT NULL,
  `hotel_name` varchar(255) DEFAULT NULL,
  `provider_hotel_id` varchar(150) DEFAULT NULL,
  `check_in_date` date NOT NULL,
  `check_out_date` date NOT NULL,
  `nights_count` tinyint(4) NOT NULL,
  `rooms_count` tinyint(4) NOT NULL DEFAULT 1,
  `adults_count` tinyint(4) NOT NULL DEFAULT 1,
  `children_count` tinyint(4) NOT NULL DEFAULT 0,
  `total_amount` decimal(10,2) NOT NULL,
  `currency` char(3) NOT NULL DEFAULT 'GBP',
  `status` enum('pending','confirmed','cancelled','no_show') NOT NULL DEFAULT 'pending',
  `cancellation_policy` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`cancellation_policy`)),
  `special_requests` text DEFAULT NULL,
  `cancelled_at` timestamp NULL DEFAULT NULL,
  `cancellation_reason` text DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_booking_ref` (`booking_reference`),
  KEY `idx_user_status` (`user_id`,`status`),
  KEY `idx_hotel` (`hotel_id`),
  KEY `provider_id` (`provider_id`),
  CONSTRAINT `hotel_bookings_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`),
  CONSTRAINT `hotel_bookings_ibfk_2` FOREIGN KEY (`provider_id`) REFERENCES `providers` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci
;

CREATE TABLE `hotel_booking_guests` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `booking_id` int(10) unsigned NOT NULL,
  `traveler_id` int(10) unsigned DEFAULT NULL,
  `is_lead` tinyint(1) NOT NULL DEFAULT 0,
  `first_name` varchar(80) NOT NULL,
  `last_name` varchar(80) NOT NULL,
  `email` varchar(180) DEFAULT NULL,
  `phone` varchar(30) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_booking` (`booking_id`),
  KEY `traveler_id` (`traveler_id`),
  CONSTRAINT `hotel_booking_guests_ibfk_1` FOREIGN KEY (`booking_id`) REFERENCES `hotel_bookings` (`id`) ON DELETE CASCADE,
  CONSTRAINT `hotel_booking_guests_ibfk_2` FOREIGN KEY (`traveler_id`) REFERENCES `travelers` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci
;

CREATE TABLE `hotel_booking_rooms` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `booking_id` int(10) unsigned NOT NULL,
  `room_type` varchar(150) NOT NULL,
  `meal_plan` varchar(50) DEFAULT NULL,
  `provider_room_id` varchar(100) DEFAULT NULL,
  `amount` decimal(10,2) NOT NULL,
  `currency` char(3) NOT NULL DEFAULT 'GBP',
  PRIMARY KEY (`id`),
  KEY `idx_booking` (`booking_id`),
  CONSTRAINT `hotel_booking_rooms_ibfk_1` FOREIGN KEY (`booking_id`) REFERENCES `hotel_bookings` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci
;

CREATE TABLE `hotel_images` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `hotel_id` int(10) unsigned NOT NULL,
  `url` varchar(500) NOT NULL,
  `caption_en` varchar(300) DEFAULT NULL,
  `caption_ar` varchar(300) DEFAULT NULL,
  `category` varchar(50) DEFAULT NULL,
  `is_main` tinyint(1) NOT NULL DEFAULT 0,
  `display_order` tinyint(4) NOT NULL DEFAULT 0,
  `width_px` smallint(6) DEFAULT NULL,
  `height_px` smallint(6) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `idx_hotel_main` (`hotel_id`,`is_main`),
  KEY `idx_hotel_order` (`hotel_id`,`display_order`),
  KEY `idx_hotel_category` (`hotel_id`,`category`),
  CONSTRAINT `hotel_images_ibfk_1` FOREIGN KEY (`hotel_id`) REFERENCES `hotels_content` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci
;

CREATE TABLE `invoices` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `invoice_number` varchar(20) NOT NULL,
  `invoice_type` enum('flight','hotel','ancillary') NOT NULL DEFAULT 'flight',
  `user_id` int(10) unsigned NOT NULL,
  `booking_type` enum('flight','hotel') NOT NULL,
  `booking_id` int(10) unsigned NOT NULL,
  `payment_id` int(10) unsigned DEFAULT NULL,
  `subtotal` decimal(10,2) NOT NULL,
  `tax_amount` decimal(10,2) NOT NULL DEFAULT 0.00,
  `service_fee` decimal(10,2) NOT NULL DEFAULT 0.00,
  `discount_amount` decimal(10,2) NOT NULL DEFAULT 0.00,
  `total_amount` decimal(10,2) NOT NULL,
  `currency` char(3) NOT NULL DEFAULT 'GBP',
  `status` enum('issued','cancelled','refunded') NOT NULL DEFAULT 'issued',
  `pdf_path` varchar(400) DEFAULT NULL,
  `issued_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_invoice_number` (`invoice_number`),
  KEY `idx_invoice_type` (`invoice_type`,`booking_id`),
  KEY `idx_user` (`user_id`),
  KEY `payment_id` (`payment_id`),
  CONSTRAINT `invoices_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`),
  CONSTRAINT `invoices_ibfk_2` FOREIGN KEY (`payment_id`) REFERENCES `payments` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci
;

CREATE TABLE `job_queue` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `job_type` varchar(50) NOT NULL,
  `payload` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL CHECK (json_valid(`payload`)),
  `status` enum('pending','processing','done','failed') NOT NULL DEFAULT 'pending',
  `attempts` tinyint(4) NOT NULL DEFAULT 0,
  `max_attempts` tinyint(4) NOT NULL DEFAULT 3,
  `error_message` text DEFAULT NULL,
  `run_at` datetime DEFAULT NULL,
  `started_at` timestamp NULL DEFAULT NULL,
  `completed_at` timestamp NULL DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `idx_status_run` (`status`,`run_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci
;

CREATE TABLE `login_attempts` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `ip_address` varchar(45) NOT NULL,
  `email` varchar(180) NOT NULL,
  `attempted_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `succeeded` tinyint(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_ip_email` (`ip_address`,`email`,`attempted_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci
;

CREATE TABLE `notification_dispatch_log` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `notification_id` int(10) unsigned NOT NULL,
  `channel` enum('email','whatsapp','push') NOT NULL,
  `recipient` varchar(200) NOT NULL,
  `status` enum('pending','sent','failed') NOT NULL DEFAULT 'pending',
  `provider_message_id` varchar(100) DEFAULT NULL,
  `error_message` text DEFAULT NULL,
  `sent_at` timestamp NULL DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `idx_notification` (`notification_id`),
  KEY `idx_status` (`status`),
  CONSTRAINT `notification_dispatch_log_ibfk_1` FOREIGN KEY (`notification_id`) REFERENCES `user_notifications` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci
;

CREATE TABLE `notification_templates` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `code` varchar(50) NOT NULL,
  `channel` enum('email','whatsapp','push') NOT NULL,
  `subject_en` varchar(200) DEFAULT NULL,
  `subject_ar` varchar(200) DEFAULT NULL,
  `body_en` text DEFAULT NULL,
  `body_ar` text DEFAULT NULL,
  `is_active` tinyint(1) NOT NULL DEFAULT 1,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_code_channel` (`code`,`channel`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci
;

CREATE TABLE `offer_cache` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `offer_request_id` varchar(100) NOT NULL,
  `offer_id` varchar(100) NOT NULL,
  `provider_id` tinyint(3) unsigned NOT NULL,
  `search_hash` varchar(64) NOT NULL,
  `offer_data` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL CHECK (json_valid(`offer_data`)),
  `total_amount` decimal(10,2) NOT NULL,
  `currency` char(3) NOT NULL,
  `expires_at` datetime NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_offer_id` (`offer_id`),
  KEY `idx_search_expires` (`search_hash`,`expires_at`),
  KEY `idx_expires_id` (`expires_at`,`id`),
  KEY `provider_id` (`provider_id`),
  CONSTRAINT `offer_cache_ibfk_1` FOREIGN KEY (`provider_id`) REFERENCES `providers` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci
;

CREATE TABLE `password_resets` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `user_id` int(10) unsigned NOT NULL,
  `token` varchar(64) NOT NULL,
  `expires_at` datetime NOT NULL,
  `used_at` timestamp NULL DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_token` (`token`),
  KEY `idx_user_id` (`user_id`),
  CONSTRAINT `password_resets_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci
;

CREATE TABLE `payments` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `booking_type` enum('flight','hotel') NOT NULL,
  `booking_id` int(10) unsigned NOT NULL,
  `user_id` int(10) unsigned NOT NULL,
  `payment_method` enum('stripe','duffel_balance') NOT NULL,
  `idempotency_key` varchar(64) NOT NULL,
  `stripe_payment_intent_id` varchar(100) DEFAULT NULL,
  `stripe_charge_id` varchar(100) DEFAULT NULL,
  `amount` decimal(10,2) NOT NULL,
  `currency` char(3) NOT NULL DEFAULT 'GBP',
  `status` enum('pending','succeeded','failed','refunded','cancelled','refund_pending','refund_failed','refund_pending_manual') NOT NULL DEFAULT 'pending' COMMENT 'Payment lifecycle status',
  `gateway_status` varchar(50) DEFAULT NULL,
  `gateway_response` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`gateway_response`)),
  `failure_reason` text DEFAULT NULL,
  `paid_at` timestamp NULL DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `duffel_payment_id` varchar(100) NOT NULL DEFAULT '' COMMENT 'Duffel payment.id if applicable',
  `payment_type` enum('stripe','duffel_balance','duffel_card') NOT NULL DEFAULT 'stripe',
  `stripe_refund_id` varchar(200) DEFAULT NULL,
  `duffel_payment_failure` varchar(500) DEFAULT NULL COMMENT 'Duffel order/payment error captured before auto-refund',
  `auto_refund_reason` varchar(255) DEFAULT NULL,
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `auto_refunded_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_idempotency` (`idempotency_key`),
  KEY `idx_booking` (`booking_type`,`booking_id`),
  KEY `idx_user_status` (`user_id`,`status`),
  KEY `idx_duffel_payment_id` (`duffel_payment_id`),
  CONSTRAINT `payments_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci
;

CREATE TABLE `permissions` (
  `id` smallint(5) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(100) NOT NULL,
  `module` varchar(50) NOT NULL,
  `description` varchar(200) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_name` (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci
;

CREATE TABLE `popular_routes` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `search_type` enum('flight','hotel') NOT NULL DEFAULT 'flight',
  `origin_airport` char(3) DEFAULT NULL,
  `destination_airport` char(3) DEFAULT NULL,
  `destination_city_id` int(10) unsigned DEFAULT NULL,
  `destination_name_ar` varchar(150) NOT NULL,
  `destination_name_en` varchar(150) NOT NULL,
  `destination_image_url` varchar(500) DEFAULT NULL,
  `lowest_price` decimal(10,2) NOT NULL,
  `currency` char(3) NOT NULL DEFAULT 'GBP',
  `valid_date` date NOT NULL,
  `display_order` tinyint(4) NOT NULL DEFAULT 0,
  `is_active` tinyint(1) NOT NULL DEFAULT 1,
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_flight_route` (`search_type`,`origin_airport`,`destination_airport`,`valid_date`),
  KEY `idx_type_active_order` (`search_type`,`is_active`,`display_order`),
  KEY `destination_city_id` (`destination_city_id`),
  CONSTRAINT `popular_routes_ibfk_1` FOREIGN KEY (`destination_city_id`) REFERENCES `cities` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci
;

CREATE TABLE `pricing_rules` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(100) NOT NULL,
  `rule_type` enum('commission','markup','service_fee','tax') NOT NULL,
  `applies_to` enum('flight','hotel','both') NOT NULL DEFAULT 'both',
  `value_type` enum('fixed','percentage') NOT NULL,
  `value` decimal(10,2) NOT NULL,
  `currency` char(3) DEFAULT NULL,
  `min_booking_amount` decimal(10,2) DEFAULT NULL,
  `max_booking_amount` decimal(10,2) DEFAULT NULL,
  `is_active` tinyint(1) NOT NULL DEFAULT 1,
  `priority` tinyint(4) NOT NULL DEFAULT 0,
  `valid_from` date DEFAULT NULL,
  `valid_until` date DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `idx_type_active` (`rule_type`,`is_active`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci
;

CREATE TABLE `providers` (
  `id` tinyint(3) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(50) NOT NULL,
  `type` enum('flight','hotel','both') NOT NULL,
  `is_active` tinyint(1) NOT NULL DEFAULT 1,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_name` (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci
;

CREATE TABLE `provider_credentials` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `provider_id` tinyint(3) unsigned NOT NULL,
  `key_name` varchar(50) NOT NULL,
  `key_value_encrypted` text NOT NULL,
  `environment` enum('sandbox','production') NOT NULL DEFAULT 'sandbox',
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_provider_key` (`provider_id`,`key_name`,`environment`),
  CONSTRAINT `provider_credentials_ibfk_1` FOREIGN KEY (`provider_id`) REFERENCES `providers` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci
;

CREATE TABLE `push_subscriptions` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `user_id` int(10) unsigned NOT NULL,
  `endpoint` text NOT NULL,
  `p256dh` varchar(200) NOT NULL,
  `auth_key` varchar(100) NOT NULL,
  `created_at` timestamp NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_user_endpoint` (`user_id`,`endpoint`(200)),
  CONSTRAINT `push_subscriptions_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
;

CREATE TABLE `rate_limits` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `identifier` varchar(45) NOT NULL,
  `identifier_type` enum('ip','user','api_key') NOT NULL DEFAULT 'ip',
  `endpoint` varchar(100) NOT NULL,
  `window_start` timestamp NOT NULL DEFAULT current_timestamp(),
  `request_count` smallint(6) NOT NULL DEFAULT 1,
  `blocked_until` timestamp NULL DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_identifier_window` (`identifier`,`identifier_type`,`endpoint`,`window_start`),
  KEY `idx_identifier_endpoint` (`identifier`,`endpoint`,`window_start`),
  KEY `idx_blocked` (`blocked_until`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci
;

CREATE TABLE `refunds` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `payment_id` int(10) unsigned NOT NULL,
  `amount` decimal(10,2) NOT NULL,
  `currency` char(3) NOT NULL DEFAULT 'GBP',
  `reason` text DEFAULT NULL,
  `stripe_refund_id` varchar(100) DEFAULT NULL,
  `status` enum('pending','succeeded','failed') NOT NULL DEFAULT 'pending',
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `idx_payment` (`payment_id`),
  CONSTRAINT `refunds_ibfk_1` FOREIGN KEY (`payment_id`) REFERENCES `payments` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci
;

CREATE TABLE `roles` (
  `id` tinyint(3) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(50) NOT NULL,
  `description` varchar(200) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_name` (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci
;

CREATE TABLE `role_permissions` (
  `role_id` tinyint(3) unsigned NOT NULL,
  `permission_id` smallint(5) unsigned NOT NULL,
  PRIMARY KEY (`role_id`,`permission_id`),
  KEY `permission_id` (`permission_id`),
  CONSTRAINT `role_permissions_ibfk_1` FOREIGN KEY (`role_id`) REFERENCES `roles` (`id`) ON DELETE CASCADE,
  CONSTRAINT `role_permissions_ibfk_2` FOREIGN KEY (`permission_id`) REFERENCES `permissions` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci
;

CREATE TABLE `saved_searches` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `user_id` int(10) unsigned NOT NULL,
  `search_type` enum('flight','hotel') NOT NULL DEFAULT 'flight',
  `label` varchar(100) DEFAULT NULL,
  `search_params` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL CHECK (json_valid(`search_params`)),
  `alert_on_price_drop` tinyint(1) NOT NULL DEFAULT 0,
  `last_checked_price` decimal(10,2) DEFAULT NULL,
  `last_checked_at` timestamp NULL DEFAULT NULL,
  `is_active` tinyint(1) NOT NULL DEFAULT 1,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `idx_user_active` (`user_id`,`is_active`),
  KEY `idx_price_alerts` (`alert_on_price_drop`,`is_active`),
  CONSTRAINT `saved_searches_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci
;

CREATE TABLE `search_logs` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `user_id` int(10) unsigned DEFAULT NULL,
  `session_key` varchar(64) DEFAULT NULL,
  `search_type` enum('flight','hotel') NOT NULL DEFAULT 'flight',
  `origin_airport` char(3) DEFAULT NULL,
  `destination_airport` char(3) DEFAULT NULL,
  `destination_city_id` int(10) unsigned DEFAULT NULL,
  `travel_date` date DEFAULT NULL,
  `return_date` date DEFAULT NULL,
  `adults_count` tinyint(4) DEFAULT NULL,
  `children_count` tinyint(4) DEFAULT NULL,
  `cabin_class` varchar(20) DEFAULT NULL,
  `results_count` smallint(6) DEFAULT NULL,
  `clicked_offer` tinyint(1) NOT NULL DEFAULT 0,
  `converted_to_booking` tinyint(1) NOT NULL DEFAULT 0,
  `booking_id` int(10) unsigned DEFAULT NULL,
  `booking_type` enum('flight','hotel') DEFAULT NULL,
  `ip_address` varchar(45) NOT NULL,
  `user_agent_hash` varchar(32) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `idx_type_date` (`search_type`,`created_at`),
  KEY `idx_route` (`origin_airport`,`destination_airport`,`travel_date`),
  KEY `idx_conversion` (`converted_to_booking`,`search_type`),
  KEY `idx_user` (`user_id`),
  KEY `destination_city_id` (`destination_city_id`),
  CONSTRAINT `search_logs_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `search_logs_ibfk_2` FOREIGN KEY (`destination_city_id`) REFERENCES `cities` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci
;

CREATE TABLE `settings` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `key_name` varchar(100) NOT NULL,
  `value` text DEFAULT NULL,
  `type` enum('string','integer','boolean','json','encrypted') NOT NULL DEFAULT 'string',
  `description` varchar(300) DEFAULT NULL,
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_key` (`key_name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci
;

CREATE TABLE `support_replies` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `ticket_id` bigint(20) unsigned NOT NULL,
  `user_id` bigint(20) unsigned DEFAULT NULL,
  `message` text NOT NULL,
  `is_admin` tinyint(1) NOT NULL DEFAULT 0,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `idx_ticket` (`ticket_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci
;

CREATE TABLE `support_tickets` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `user_id` int(10) unsigned NOT NULL,
  `booking_type` enum('flight','hotel') DEFAULT NULL,
  `booking_id` int(10) unsigned DEFAULT NULL,
  `subject` varchar(200) NOT NULL,
  `status` enum('open','pending','resolved','closed') NOT NULL DEFAULT 'open',
  `priority` enum('low','medium','high','urgent') NOT NULL DEFAULT 'medium',
  `assigned_to` int(10) unsigned DEFAULT NULL,
  `resolved_at` timestamp NULL DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `idx_user_status` (`user_id`,`status`),
  KEY `idx_assigned` (`assigned_to`),
  CONSTRAINT `support_tickets_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci
;

CREATE TABLE `ticket_attachments` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `ticket_id` int(10) unsigned NOT NULL,
  `message_id` int(10) unsigned NOT NULL,
  `file_name` varchar(255) NOT NULL,
  `file_path` varchar(400) NOT NULL,
  `file_size` int(11) DEFAULT NULL,
  `mime_type` varchar(100) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `idx_ticket` (`ticket_id`),
  KEY `message_id` (`message_id`),
  CONSTRAINT `ticket_attachments_ibfk_1` FOREIGN KEY (`ticket_id`) REFERENCES `support_tickets` (`id`) ON DELETE CASCADE,
  CONSTRAINT `ticket_attachments_ibfk_2` FOREIGN KEY (`message_id`) REFERENCES `ticket_messages` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci
;

CREATE TABLE `ticket_messages` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `ticket_id` int(10) unsigned NOT NULL,
  `sender_id` int(10) unsigned NOT NULL,
  `sender_type` enum('user','agent','system') NOT NULL DEFAULT 'user',
  `message` text NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `idx_ticket` (`ticket_id`),
  CONSTRAINT `ticket_messages_ibfk_1` FOREIGN KEY (`ticket_id`) REFERENCES `support_tickets` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci
;

CREATE TABLE `travelers` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `user_id` int(10) unsigned NOT NULL,
  `title` enum('mr','ms','mrs','miss','dr') DEFAULT NULL,
  `first_name` varchar(80) NOT NULL,
  `middle_name` varchar(80) DEFAULT NULL,
  `last_name` varchar(80) NOT NULL,
  `gender` enum('male','female') NOT NULL,
  `date_of_birth` date NOT NULL,
  `nationality` varchar(60) NOT NULL,
  `country` varchar(80) DEFAULT NULL,
  `phone_country_code` varchar(6) NOT NULL DEFAULT '+',
  `phone_number` varchar(20) NOT NULL DEFAULT '',
  `phone` varchar(30) DEFAULT NULL,
  `email` varchar(180) DEFAULT NULL,
  `document_type` enum('passport','civil_id','national_id') NOT NULL DEFAULT 'passport',
  `document_number` varchar(40) DEFAULT NULL,
  `issue_date` date DEFAULT NULL,
  `expiry_date` date NOT NULL,
  `document_issue` date DEFAULT NULL,
  `document_expiry` date DEFAULT NULL,
  `document_country` varchar(80) DEFAULT NULL,
  `is_default` tinyint(1) NOT NULL DEFAULT 0,
  `is_primary_contact` tinyint(1) NOT NULL DEFAULT 0,
  `relationship_to_user` enum('self','spouse','child','parent','other') DEFAULT NULL,
  `notes` text DEFAULT NULL,
  `archived_at` timestamp NULL DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `idx_user_archived` (`user_id`,`archived_at`),
  CONSTRAINT `travelers_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci
;

CREATE TABLE `traveler_documents` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `traveler_id` int(10) unsigned NOT NULL,
  `doc_type` enum('passport','national_id','residence') NOT NULL,
  `doc_number` varchar(30) NOT NULL,
  `issuing_country` char(2) NOT NULL,
  `expiry_date` date NOT NULL,
  `is_primary` tinyint(1) NOT NULL DEFAULT 0,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `idx_traveler` (`traveler_id`),
  CONSTRAINT `traveler_documents_ibfk_1` FOREIGN KEY (`traveler_id`) REFERENCES `travelers` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci
;

CREATE TABLE `traveler_frequent_flyers` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `traveler_id` int(10) unsigned NOT NULL,
  `airline_code` char(2) NOT NULL,
  `ff_number` varchar(30) NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `idx_traveler` (`traveler_id`),
  CONSTRAINT `traveler_frequent_flyers_ibfk_1` FOREIGN KEY (`traveler_id`) REFERENCES `travelers` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci
;

CREATE TABLE `users` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `email` varchar(180) NOT NULL,
  `password` varchar(255) NOT NULL,
  `first_name` varchar(80) NOT NULL,
  `last_name` varchar(80) NOT NULL,
  `role` enum('user','admin','super_admin') NOT NULL DEFAULT 'user',
  `phone_country_code` varchar(6) NOT NULL,
  `phone_number` varchar(20) NOT NULL,
  `is_verified` tinyint(1) NOT NULL DEFAULT 0,
  `is_active` tinyint(1) NOT NULL DEFAULT 1,
  `email_verified_at` timestamp NULL DEFAULT NULL,
  `last_login_at` timestamp NULL DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_email` (`email`),
  KEY `idx_phone` (`phone_number`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
;

CREATE TABLE `user_notifications` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `user_id` int(10) unsigned NOT NULL,
  `template_id` int(10) unsigned DEFAULT NULL,
  `channel` enum('email','whatsapp','push') NOT NULL,
  `title_ar` varchar(200) DEFAULT NULL,
  `title_en` varchar(200) DEFAULT NULL,
  `body_ar` text DEFAULT NULL,
  `body_en` text DEFAULT NULL,
  `is_read` tinyint(1) NOT NULL DEFAULT 0,
  `read_at` timestamp NULL DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `idx_user_read` (`user_id`,`is_read`),
  CONSTRAINT `user_notifications_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci
;

CREATE TABLE `user_notification_preferences` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `user_id` int(10) unsigned NOT NULL,
  `channel` enum('email','whatsapp','push') NOT NULL,
  `event_type` varchar(50) NOT NULL,
  `is_enabled` tinyint(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_user_channel_event` (`user_id`,`channel`,`event_type`),
  CONSTRAINT `user_notification_preferences_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci
;

CREATE TABLE `user_sessions` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `user_id` int(10) unsigned NOT NULL,
  `session_token` varchar(64) NOT NULL,
  `ip_address` varchar(45) NOT NULL,
  `user_agent` text DEFAULT NULL,
  `last_active_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `expires_at` datetime NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_token` (`session_token`),
  KEY `idx_user_id` (`user_id`),
  CONSTRAINT `user_sessions_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci
;

CREATE TABLE `user_wallets` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `user_id` int(10) unsigned NOT NULL,
  `balance` decimal(12,2) NOT NULL DEFAULT 0.00,
  `currency` char(3) NOT NULL DEFAULT 'GBP',
  `updated_at` datetime NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `user_id` (`user_id`),
  CONSTRAINT `fk_wallet_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci
;

CREATE TABLE `wallet_transactions` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `user_id` int(10) unsigned NOT NULL,
  `type` enum('credit','debit') NOT NULL,
  `amount` decimal(12,2) NOT NULL,
  `currency` char(3) NOT NULL DEFAULT 'GBP',
  `balance_after` decimal(12,2) NOT NULL,
  `description` varchar(255) NOT NULL DEFAULT '',
  `reference` varchar(100) DEFAULT NULL COMMENT 'booking ref, payment id, etc.',
  `created_at` datetime NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `idx_wallet_tx_user` (`user_id`),
  CONSTRAINT `fk_wallet_tx_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci
;

CREATE TABLE `webhook_logs` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `source` enum('stripe','duffel','ratehawk') NOT NULL,
  `event_id` varchar(100) NOT NULL,
  `event_type` varchar(100) DEFAULT NULL,
  `signature_valid` tinyint(1) NOT NULL DEFAULT 0,
  `processed` tinyint(1) NOT NULL DEFAULT 0,
  `processing_result` varchar(100) DEFAULT NULL,
  `payload` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`payload`)),
  `processed_at` timestamp NULL DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_source_event` (`source`,`event_id`),
  KEY `idx_processed` (`processed`,`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci
;

CREATE TABLE `whatsapp_providers` (
  `id` tinyint(3) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(50) NOT NULL,
  `config_encrypted` text NOT NULL,
  `is_active` tinyint(1) NOT NULL DEFAULT 0,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_name` (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci
;

CREATE TABLE `whatsapp_templates` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `provider_id` tinyint(3) unsigned NOT NULL,
  `template_code` varchar(50) NOT NULL,
  `provider_template_name` varchar(100) NOT NULL,
  `language` char(5) NOT NULL DEFAULT 'ar',
  `params_schema` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`params_schema`)),
  `is_active` tinyint(1) NOT NULL DEFAULT 1,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_provider_code_lang` (`provider_id`,`template_code`,`language`),
  CONSTRAINT `whatsapp_templates_ibfk_1` FOREIGN KEY (`provider_id`) REFERENCES `whatsapp_providers` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci
;

