CREATE TABLE travelers (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  user_id INT UNSIGNED NOT NULL,
  first_name VARCHAR(80) NOT NULL,
  middle_name VARCHAR(80) NULL,
  last_name VARCHAR(80) NOT NULL,
  gender ENUM('male','female') NOT NULL,
  date_of_birth DATE NOT NULL,
  nationality VARCHAR(60) NOT NULL,
  country VARCHAR(80) NULL,
  phone_country_code VARCHAR(6) NOT NULL DEFAULT '+',
  phone_number VARCHAR(20) NOT NULL DEFAULT '',
  phone VARCHAR(30) NULL,
  email VARCHAR(180) NULL,
  document_type ENUM('passport','civil_id','national_id') NOT NULL DEFAULT 'passport',
  document_number VARCHAR(40) NULL,
  issue_date DATE NULL,
  expiry_date DATE NOT NULL,
  document_issue DATE NULL,
  document_expiry DATE NULL,
  document_country VARCHAR(80) NULL,
  is_default BOOLEAN NOT NULL DEFAULT 0,
  is_primary_contact BOOLEAN NOT NULL DEFAULT 0,
  relationship_to_user ENUM('self','spouse','child','parent','other') NULL,
  notes TEXT NULL,
  archived_at TIMESTAMP NULL,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP NOT NULL DEFAULT NOW() ON UPDATE NOW(),
  PRIMARY KEY (id),
  KEY idx_user_archived (user_id, archived_at),
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
