CREATE TABLE flight_bookings (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  user_id INT UNSIGNED NOT NULL,
  provider_id TINYINT UNSIGNED NOT NULL,
  booking_reference VARCHAR(30) NOT NULL,
  provider_order_id VARCHAR(100) NULL,
  trip_type ENUM('one_way','round_trip','multi_city') NOT NULL,
  cabin_class ENUM('economy','premium_economy','business','first') NOT NULL DEFAULT 'economy',
  adults_count TINYINT NOT NULL DEFAULT 1,
  children_count TINYINT NOT NULL DEFAULT 0,
  infants_count TINYINT NOT NULL DEFAULT 0,
  origin_airport CHAR(3) NOT NULL,
  destination_airport CHAR(3) NOT NULL,
  departure_at DATETIME NOT NULL,
  return_at DATETIME NULL,
  total_amount DECIMAL(10,2) NOT NULL,
  currency CHAR(3) NOT NULL DEFAULT 'GBP',
  status ENUM('pending','confirmed','cancelled','changed') NOT NULL DEFAULT 'pending',
  cancellation_reason TEXT NULL,
  cancelled_at TIMESTAMP NULL,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP NOT NULL DEFAULT NOW() ON UPDATE NOW(),
  PRIMARY KEY (id),
  UNIQUE KEY uq_booking_ref (booking_reference),
  KEY idx_user_status (user_id, status),
  KEY idx_provider (provider_id),
  FOREIGN KEY (user_id) REFERENCES users(id),
  FOREIGN KEY (provider_id) REFERENCES providers(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
