CREATE TABLE booking_sessions (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  session_key VARCHAR(64) NOT NULL,
  user_id INT UNSIGNED NOT NULL,
  booking_type ENUM('flight','hotel') NOT NULL DEFAULT 'flight',
  current_step VARCHAR(30) NOT NULL DEFAULT 'search',
  provider_offer_id VARCHAR(100) NULL,
  offer_expires_at DATETIME NULL,
  prebook_session_id VARCHAR(200) NULL,
  passengers_data JSON NULL,
  services_data JSON NULL,
  guests_data JSON NULL,
  pricing_snapshot JSON NULL,
  coupon_code VARCHAR(30) NULL,
  payment_intent_id VARCHAR(100) NULL,
  idempotency_key VARCHAR(64) NULL,
  expires_at DATETIME NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP NOT NULL DEFAULT NOW() ON UPDATE NOW(),
  PRIMARY KEY (id),
  UNIQUE KEY uq_session_key (session_key),
  KEY idx_user_type (user_id, booking_type),
  KEY idx_expires (expires_at),
  KEY idx_payment_intent (payment_intent_id),
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
