CREATE TABLE hotel_bookings (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  user_id INT UNSIGNED NOT NULL,
  provider_id TINYINT UNSIGNED NOT NULL,
  booking_reference VARCHAR(30) NOT NULL,
  provider_booking_id VARCHAR(100) NULL,
  hotel_id INT UNSIGNED NOT NULL,
  check_in_date DATE NOT NULL,
  check_out_date DATE NOT NULL,
  nights_count TINYINT NOT NULL,
  rooms_count TINYINT NOT NULL DEFAULT 1,
  adults_count TINYINT NOT NULL DEFAULT 1,
  children_count TINYINT NOT NULL DEFAULT 0,
  total_amount DECIMAL(10,2) NOT NULL,
  currency CHAR(3) NOT NULL DEFAULT 'GBP',
  status ENUM('pending','confirmed','cancelled','no_show') NOT NULL DEFAULT 'pending',
  cancellation_policy JSON NULL,
  special_requests TEXT NULL,
  cancelled_at TIMESTAMP NULL,
  cancellation_reason TEXT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP NOT NULL DEFAULT NOW() ON UPDATE NOW(),
  PRIMARY KEY (id),
  UNIQUE KEY uq_booking_ref (booking_reference),
  KEY idx_user_status (user_id, status),
  KEY idx_hotel (hotel_id),
  FOREIGN KEY (user_id) REFERENCES users(id),
  FOREIGN KEY (provider_id) REFERENCES providers(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
