CREATE TABLE hotels_content (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  provider_id TINYINT UNSIGNED NOT NULL,
  provider_hotel_id VARCHAR(100) NOT NULL,
  name_en VARCHAR(300) NOT NULL,
  name_ar VARCHAR(300) NULL,
  star_rating TINYINT NULL,
  guest_rating DECIMAL(3,1) NULL,
  reviews_count INT NULL,
  address_en TEXT NULL,
  address_ar TEXT NULL,
  city_id INT UNSIGNED NULL,
  country_id SMALLINT UNSIGNED NULL,
  latitude DECIMAL(9,6) NULL,
  longitude DECIMAL(9,6) NULL,
  distance_to_center_km DECIMAL(5,2) NULL,
  images_count TINYINT NOT NULL DEFAULT 0,
  main_image_url VARCHAR(500) NULL,
  amenities JSON NULL,
  description_en TEXT NULL,
  description_ar TEXT NULL,
  policies JSON NULL,
  children_policy JSON NULL,
  is_active BOOLEAN NOT NULL DEFAULT 1,
  content_updated_at TIMESTAMP NULL,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  PRIMARY KEY (id),
  UNIQUE KEY uq_provider_hotel (provider_id, provider_hotel_id),
  KEY idx_city (city_id),
  KEY idx_country (country_id),
  KEY idx_star_active (star_rating, is_active),
  KEY idx_guest_rating (guest_rating),
  FOREIGN KEY (provider_id) REFERENCES providers(id),
  FOREIGN KEY (city_id) REFERENCES cities(id) ON DELETE SET NULL,
  FOREIGN KEY (country_id) REFERENCES countries(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
