CREATE TABLE invoices (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  invoice_number VARCHAR(20) NOT NULL,
  invoice_type ENUM('flight','hotel','ancillary') NOT NULL DEFAULT 'flight',
  user_id INT UNSIGNED NOT NULL,
  booking_type ENUM('flight','hotel') NOT NULL,
  booking_id INT UNSIGNED NOT NULL,
  payment_id INT UNSIGNED NULL,
  subtotal DECIMAL(10,2) NOT NULL,
  tax_amount DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  service_fee DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  discount_amount DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  total_amount DECIMAL(10,2) NOT NULL,
  currency CHAR(3) NOT NULL DEFAULT 'GBP',
  status ENUM('issued','cancelled','refunded') NOT NULL DEFAULT 'issued',
  pdf_path VARCHAR(400) NULL,
  issued_at TIMESTAMP NOT NULL DEFAULT NOW(),
  PRIMARY KEY (id),
  UNIQUE KEY uq_invoice_number (invoice_number),
  KEY idx_invoice_type (invoice_type, booking_id),
  KEY idx_user (user_id),
  FOREIGN KEY (user_id) REFERENCES users(id),
  FOREIGN KEY (payment_id) REFERENCES payments(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
