CREATE TABLE search_logs (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  user_id INT UNSIGNED NULL,
  session_key VARCHAR(64) NULL,
  search_type ENUM('flight','hotel') NOT NULL DEFAULT 'flight',
  origin_airport CHAR(3) NULL,
  destination_airport CHAR(3) NULL,
  destination_city_id INT UNSIGNED NULL,
  travel_date DATE NULL,
  return_date DATE NULL,
  adults_count TINYINT NULL,
  children_count TINYINT NULL,
  cabin_class VARCHAR(20) NULL,
  results_count SMALLINT NULL,
  clicked_offer BOOLEAN NOT NULL DEFAULT 0,
  converted_to_booking BOOLEAN NOT NULL DEFAULT 0,
  booking_id INT UNSIGNED NULL,
  booking_type ENUM('flight','hotel') NULL,
  ip_address VARCHAR(45) NOT NULL,
  user_agent_hash VARCHAR(32) NULL,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  PRIMARY KEY (id),
  KEY idx_type_date (search_type, created_at),
  KEY idx_route (origin_airport, destination_airport, travel_date),
  KEY idx_conversion (converted_to_booking, search_type),
  KEY idx_user (user_id),
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL,
  FOREIGN KEY (destination_city_id) REFERENCES cities(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
